package org.doubleluck.radish_purchase_api.model.po;

import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Builder
@NoArgsConstructor
@ToString
public class GoodsPic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic.id
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic.uri
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic.name
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic.deleted_flag
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    private Byte deletedFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic.id
     *
     * @return the value of goods_pic.id
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic.id
     *
     * @param id the value for goods_pic.id
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic.uri
     *
     * @return the value of goods_pic.uri
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic.uri
     *
     * @param uri the value for goods_pic.uri
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic.name
     *
     * @return the value of goods_pic.name
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic.name
     *
     * @param name the value for goods_pic.name
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic.created_at
     *
     * @return the value of goods_pic.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic.created_at
     *
     * @param createdAt the value for goods_pic.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic.deleted_flag
     *
     * @return the value of goods_pic.deleted_flag
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    public Byte getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic.deleted_flag
     *
     * @param deletedFlag the value for goods_pic.deleted_flag
     *
     * @mbg.generated Mon Aug 27 11:50:06 CST 2018
     */
    public void setDeletedFlag(Byte deletedFlag) {
        this.deletedFlag = deletedFlag;
    }
}