package org.doubleluck.radish_purchase_api.model.po;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.seller_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Long sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.classify_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Long classifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Long statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.modified_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Date modifiedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.delete_flag
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Byte deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.seller_id
     *
     * @return the value of goods.seller_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.seller_id
     *
     * @param sellerId the value for goods.seller_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.classify_id
     *
     * @return the value of goods.classify_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Long getClassifyId() {
        return classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.classify_id
     *
     * @param classifyId the value for goods.classify_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setClassifyId(Long classifyId) {
        this.classifyId = classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status_id
     *
     * @return the value of goods.status_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Long getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status_id
     *
     * @param statusId the value for goods.status_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setStatusId(Long statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.created_at
     *
     * @return the value of goods.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.created_at
     *
     * @param createdAt the value for goods.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.modified_at
     *
     * @return the value of goods.modified_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.modified_at
     *
     * @param modifiedAt the value for goods.modified_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.delete_flag
     *
     * @return the value of goods.delete_flag
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.delete_flag
     *
     * @param deleteFlag the value for goods.delete_flag
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}