package org.doubleluck.radish_purchase_api.model.po;

import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Builder
@ToString
@NoArgsConstructor
public class GoodsPicRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic_rel.id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic_rel.goods_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic_rel.goods_detail_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Long goodsDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic_rel.rank
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic_rel.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pic_rel.delete_flag
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Byte deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic_rel.id
     *
     * @return the value of goods_pic_rel.id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic_rel.id
     *
     * @param id the value for goods_pic_rel.id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic_rel.goods_id
     *
     * @return the value of goods_pic_rel.goods_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic_rel.goods_id
     *
     * @param goodsId the value for goods_pic_rel.goods_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic_rel.goods_detail_id
     *
     * @return the value of goods_pic_rel.goods_detail_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Long getGoodsDetailId() {
        return goodsDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic_rel.goods_detail_id
     *
     * @param goodsDetailId the value for goods_pic_rel.goods_detail_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setGoodsDetailId(Long goodsDetailId) {
        this.goodsDetailId = goodsDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic_rel.rank
     *
     * @return the value of goods_pic_rel.rank
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic_rel.rank
     *
     * @param rank the value for goods_pic_rel.rank
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic_rel.created_at
     *
     * @return the value of goods_pic_rel.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic_rel.created_at
     *
     * @param createdAt the value for goods_pic_rel.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pic_rel.delete_flag
     *
     * @return the value of goods_pic_rel.delete_flag
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pic_rel.delete_flag
     *
     * @param deleteFlag the value for goods_pic_rel.delete_flag
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}