package org.doubleluck.radish_purchase_api.model.po;

import java.util.Date;

public class GoodsClassify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_classify.id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_classify.user_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_classify.name
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_classify.desc
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_classify.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_classify.delete_flag
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    private Byte deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_classify.id
     *
     * @return the value of goods_classify.id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_classify.id
     *
     * @param id the value for goods_classify.id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_classify.user_id
     *
     * @return the value of goods_classify.user_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_classify.user_id
     *
     * @param userId the value for goods_classify.user_id
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_classify.name
     *
     * @return the value of goods_classify.name
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_classify.name
     *
     * @param name the value for goods_classify.name
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_classify.desc
     *
     * @return the value of goods_classify.desc
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_classify.desc
     *
     * @param desc the value for goods_classify.desc
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_classify.created_at
     *
     * @return the value of goods_classify.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_classify.created_at
     *
     * @param createdAt the value for goods_classify.created_at
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_classify.delete_flag
     *
     * @return the value of goods_classify.delete_flag
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_classify.delete_flag
     *
     * @param deleteFlag the value for goods_classify.delete_flag
     *
     * @mbg.generated Mon Aug 27 11:50:05 CST 2018
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}