package org.doubleluck.radish_purchase_api.repository;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.doubleluck.radish_purchase_api.model.example.GoodsClassifyExample;
import org.doubleluck.radish_purchase_api.model.po.GoodsClassify;

public interface GoodsClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @SelectProvider(type=GoodsClassifySqlProvider.class, method="countByExample")
    long countByExample(GoodsClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @DeleteProvider(type=GoodsClassifySqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Delete({
        "delete from goods_classify",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Insert({
        "insert into goods_classify (user_id, `name`, ",
        "`desc`, created_at, ",
        "delete_flag)",
        "values (#{userId,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{desc,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{deleteFlag,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(GoodsClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @InsertProvider(type=GoodsClassifySqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(GoodsClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @SelectProvider(type=GoodsClassifySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="desc", property="desc", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_flag", property="deleteFlag", jdbcType=JdbcType.TINYINT)
    })
    List<GoodsClassify> selectByExample(GoodsClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Select({
        "select",
        "id, user_id, `name`, `desc`, created_at, delete_flag",
        "from goods_classify",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="desc", property="desc", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_flag", property="deleteFlag", jdbcType=JdbcType.TINYINT)
    })
    GoodsClassify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=GoodsClassifySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsClassify record, @Param("example") GoodsClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=GoodsClassifySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsClassify record, @Param("example") GoodsClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=GoodsClassifySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_classify
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Update({
        "update goods_classify",
        "set user_id = #{userId,jdbcType=BIGINT},",
          "`name` = #{name,jdbcType=VARCHAR},",
          "`desc` = #{desc,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "delete_flag = #{deleteFlag,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GoodsClassify record);
}