package org.doubleluck.radish_purchase_api.repository;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.doubleluck.radish_purchase_api.model.example.GoodsOperationLogExample;
import org.doubleluck.radish_purchase_api.model.po.GoodsOperationLog;

public interface GoodsOperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @SelectProvider(type=GoodsOperationLogSqlProvider.class, method="countByExample")
    long countByExample(GoodsOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @DeleteProvider(type=GoodsOperationLogSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Delete({
        "delete from goods_operation_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Insert({
        "insert into goods_operation_log (goods_id, user_id, ",
        "created_at, delete_flag, ",
        "`desc`)",
        "values (#{goodsId,jdbcType=BIGINT}, #{userId,jdbcType=BIGINT}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{deleteFlag,jdbcType=TINYINT}, ",
        "#{desc,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(GoodsOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @InsertProvider(type=GoodsOperationLogSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(GoodsOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @SelectProvider(type=GoodsOperationLogSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.BIGINT),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_flag", property="deleteFlag", jdbcType=JdbcType.TINYINT),
        @Result(column="desc", property="desc", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<GoodsOperationLog> selectByExampleWithBLOBs(GoodsOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @SelectProvider(type=GoodsOperationLogSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.BIGINT),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_flag", property="deleteFlag", jdbcType=JdbcType.TINYINT)
    })
    List<GoodsOperationLog> selectByExample(GoodsOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Select({
        "select",
        "id, goods_id, user_id, created_at, delete_flag, `desc`",
        "from goods_operation_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.BIGINT),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_flag", property="deleteFlag", jdbcType=JdbcType.TINYINT),
        @Result(column="desc", property="desc", jdbcType=JdbcType.LONGVARCHAR)
    })
    GoodsOperationLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=GoodsOperationLogSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsOperationLog record, @Param("example") GoodsOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=GoodsOperationLogSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") GoodsOperationLog record, @Param("example") GoodsOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=GoodsOperationLogSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsOperationLog record, @Param("example") GoodsOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=GoodsOperationLogSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Update({
        "update goods_operation_log",
        "set goods_id = #{goodsId,jdbcType=BIGINT},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "delete_flag = #{deleteFlag,jdbcType=TINYINT},",
          "`desc` = #{desc,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(GoodsOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Update({
        "update goods_operation_log",
        "set goods_id = #{goodsId,jdbcType=BIGINT},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "delete_flag = #{deleteFlag,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GoodsOperationLog record);
}