package org.doubleluck.radish_purchase_api.repository;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.doubleluck.radish_purchase_api.model.example.GoodsPicRelExample;
import org.doubleluck.radish_purchase_api.model.po.GoodsPicRel;

public interface GoodsPicRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @SelectProvider(type=GoodsPicRelSqlProvider.class, method="countByExample")
    long countByExample(GoodsPicRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @DeleteProvider(type=GoodsPicRelSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsPicRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Delete({
        "delete from goods_pic_rel",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Insert({
        "insert into goods_pic_rel (goods_id, goods_detail_id, ",
        "`rank`, created_at, ",
        "delete_flag)",
        "values (#{goodsId,jdbcType=BIGINT}, #{goodsDetailId,jdbcType=BIGINT}, ",
        "#{rank,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{deleteFlag,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(GoodsPicRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @InsertProvider(type=GoodsPicRelSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(GoodsPicRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @SelectProvider(type=GoodsPicRelSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_detail_id", property="goodsDetailId", jdbcType=JdbcType.BIGINT),
        @Result(column="rank", property="rank", jdbcType=JdbcType.INTEGER),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_flag", property="deleteFlag", jdbcType=JdbcType.TINYINT)
    })
    List<GoodsPicRel> selectByExample(GoodsPicRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Select({
        "select",
        "id, goods_id, goods_detail_id, `rank`, created_at, delete_flag",
        "from goods_pic_rel",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_detail_id", property="goodsDetailId", jdbcType=JdbcType.BIGINT),
        @Result(column="rank", property="rank", jdbcType=JdbcType.INTEGER),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_flag", property="deleteFlag", jdbcType=JdbcType.TINYINT)
    })
    GoodsPicRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=GoodsPicRelSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsPicRel record, @Param("example") GoodsPicRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=GoodsPicRelSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsPicRel record, @Param("example") GoodsPicRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=GoodsPicRelSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsPicRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pic_rel
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Update({
        "update goods_pic_rel",
        "set goods_id = #{goodsId,jdbcType=BIGINT},",
          "goods_detail_id = #{goodsDetailId,jdbcType=BIGINT},",
          "`rank` = #{rank,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "delete_flag = #{deleteFlag,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GoodsPicRel record);
}