package org.doubleluck.radish_purchase_api.repository;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.doubleluck.radish_purchase_api.model.example.OrderOperationLogExample;
import org.doubleluck.radish_purchase_api.model.po.OrderOperationLog;

public interface OrderOperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @SelectProvider(type=OrderOperationLogSqlProvider.class, method="countByExample")
    long countByExample(OrderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @DeleteProvider(type=OrderOperationLogSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Delete({
        "delete from order_operation_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Insert({
        "insert into order_operation_log (order_id, user_id, ",
        "created_at, delete_flag, ",
        "`desc`)",
        "values (#{orderId,jdbcType=BIGINT}, #{userId,jdbcType=BIGINT}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{deleteFlag,jdbcType=TINYINT}, ",
        "#{desc,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(OrderOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @InsertProvider(type=OrderOperationLogSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(OrderOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @SelectProvider(type=OrderOperationLogSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.BIGINT),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_flag", property="deleteFlag", jdbcType=JdbcType.TINYINT),
        @Result(column="desc", property="desc", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<OrderOperationLog> selectByExampleWithBLOBs(OrderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @SelectProvider(type=OrderOperationLogSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.BIGINT),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_flag", property="deleteFlag", jdbcType=JdbcType.TINYINT)
    })
    List<OrderOperationLog> selectByExample(OrderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Select({
        "select",
        "id, order_id, user_id, created_at, delete_flag, `desc`",
        "from order_operation_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.BIGINT),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="delete_flag", property="deleteFlag", jdbcType=JdbcType.TINYINT),
        @Result(column="desc", property="desc", jdbcType=JdbcType.LONGVARCHAR)
    })
    OrderOperationLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=OrderOperationLogSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OrderOperationLog record, @Param("example") OrderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=OrderOperationLogSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") OrderOperationLog record, @Param("example") OrderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=OrderOperationLogSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OrderOperationLog record, @Param("example") OrderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @UpdateProvider(type=OrderOperationLogSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Update({
        "update order_operation_log",
        "set order_id = #{orderId,jdbcType=BIGINT},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "delete_flag = #{deleteFlag,jdbcType=TINYINT},",
          "`desc` = #{desc,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(OrderOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operation_log
     *
     * @mbg.generated Mon Aug 27 15:04:52 CST 2018
     */
    @Update({
        "update order_operation_log",
        "set order_id = #{orderId,jdbcType=BIGINT},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "delete_flag = #{deleteFlag,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrderOperationLog record);
}