  java:
    io:
      tmpdir: /data/tmp

  server:
    port: 8123
# jdbc
  spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: PQzx1Vj46atp
      url: jdbc:mysql://localhost:3306/radish_purchase_mp?useSSL=true&useUnicode=true&characterEncoding=UTF-8

# page helper
  pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql

  session:
    login:
      path:
        exclude: /api/v1.0/oauth
